apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-

resources:
  - ../../base

replicas:
  - name: react-app
    count: 1

patchesStrategicMerge:
  - configmap.yaml

images:
  - name: react-app
    newName: registry.example.com/react-app
    newTag: dev 