apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-

resources:
  - ../../base
  - ingress.yaml

patchesStrategicMerge:
  - configmap.yaml

images:
  - name: react-app
    newName: registry.example.com/react-app
    newTag: stable 