apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: react-app
spec:
  selector:
    app: react-app
    environment: blue  # This will be switched between blue and green
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP 